#!/bin/bash
set -e

swagger-cli bundle -r ../backend/openapi.yaml -o openapi-deref.yaml
rm -rf delightool-api-client/ || true
openapi-python-client generate --config $PWD/python-gen.yaml --path openapi-deref.yaml

cp LICENSE delightool-api-client/
sed -i '5 i license = "Apache-2.0"' delightool-api-client/pyproject.toml

sed -i 's/authors = \[\]/authors = \["Ruben Fiszel <ruben@rubenfiszel.com>"\]/g' delightool-api-client/pyproject.toml

echo "# Autogenerated Delightool OpenApi Client" >> delightool-api-client/README.md.tmp
echo "This is the raw autogenerated api client. You are most likely more interested \
in [wmill](https://pypi.org/project/wmill/) which leverages this client to offer an \
user friendly experience. We use \
[this openapi python client generator](https://github.com/openapi-generators/openapi-python-client/)"\
>> delightool-api-client/README.md.tmp

echo "" >> delightool-api-client/README.md.tmp


head -n -13 delightool-api-client/README.md >> delightool-api-client/README.md.tmp
mv delightool-api-client/README.md.tmp delightool-api-client/README.md

cd delightool-api-client && poetry build
cd .. && poetry build
